### ISSUE TITLE
Incorrect usage of TestNG expectedExceptions

### ISSUE THREAD

**Issue by WojTechM** [michalakadam/LetterAnalyzer#1]
When you are using "expectedExceptions" don't bother creating failing assert statements. When no exception is thrown, test will automatically fail.

https://github.com/michalakadam/LetterAnalyzer/blob/356d1ba358f9d907bcf281c5d69628607c8d01ea/src/test/java/pl/michalak/adam/letteranalyzer/input/InputValidatorTest.java#L28

**Comment by michalakadam** [comment]
True!
