### ISSUE TITLE
App crashed when entered empty string

### ISSUE THREAD

**Issue by WojTechM** [michalakadam/LetterAnalyzer#2]
Input stream is closed after first 'this.keyboard.nextLine();' call in KeyboardMapper, thus when you are trying to ask for input again, application crashes.
Also, recursive call to 
            return collectUserInput(); // class ProgramFlowController
in makes it easy for user to cause StackOverflowError.

https://github.com/michalakadam/LetterAnalyzer/blob/356d1ba358f9d907bcf281c5d69628607c8d01ea/src/main/java/pl/michalak/adam/letteranalyzer/ProgramFlowController.java#L52

**Comment by michalakadam** [comment]
I moved closing Scanner to another method.
